colors0 = {
  'diffEditor.border': '#7160',
  'diffEditor.insertedTextBorder': '#7160',
  'diffEditor.removedTextBorder': '#7160',
  'statusBar.debuggingBorder': '#7160',
  'statusBar.noFolderBorder': '#7160',
};
colors1 = {
  'notifications.border': '#7161',
  'editor.lineHighlightBackground': '#15E1',
  'editor.lineHighlightBorder': '#E111',
  'editor.rangeHighlightBorder': '#7161',
  'editorIndentGuide.background': '#4AE1',
  'menu.border': '#7161',
  'notificationCenter.border': '#7161',
  'notificationToast.border': '#7161',
  'pickerGroup.border': '#7161',
  'statusBar.border': '#FC61',
  'textBlockQuote.border': '#7161',
  'titleBar.border': '#FC61',
};
colors2 = {
  'editorWhitespace.foreground': '#DCB2',
  'peekViewResult.background': '#52A2',
};
colors3 = {
  'inputValidation.errorBackground': '#7223',
  'inputValidation.infoBackground': '#2353',
  'inputValidation.warningBackground': '#7523',
  'editor.hoverHighlightBackground': '#38A3',
  'editor.wordHighlightBackground': '#8DA3',
  'editor.wordHighlightStrongBackground': '#E473',
  'list.inactiveSelectionBackground': '#7163',
  'editorHoverWidget.border': '#DCB3',
  'list.inactiveFocusBackground': '#7163',
  'editorIndentGuide.activeBackground': '#4AE3',
  'tab.activeBackground': '#7163',
  'debugExceptionWidget.border': '#DCB3',
  'diffEditor.insertedTextBackground': '#8DA3',
  'diffEditor.removedTextBackground': '#E473',
  'editorCodeLens.foreground': '#DCB3',
  'list.dropBackground': '#38A3',
  'merge.commonContentBackground': '#8F73',
  'merge.currentContentBackground': '#38A3',
  'merge.incomingContentBackground': '#E473',
  'panel.border': '#DCB3',
  'panelInput.border': '#7163',
  'settings.dropdownBorder': '#FC63',
  'settings.dropdownListBorder': '#FC63',
  'settings.checkboxBorder': '#FC63',
  'settings.numberInputBorder': '#FC63',
  'settings.textInputBorder': '#FC63',
};
colors4 = {
  'editorWarning.border': '#BD24',
  'editorHint.border': '#FC64',
  'editorError.border': '#F154',
  'editor.findMatchHighlightBackground': '#38A4',
  'peekViewResult.selectionBackground': '#42B4',
  'tab.unfocusedHoverBackground': '#52A4',
  'activityBar.border': '#FC64',
  'editorBracketMatch.background': '#AE44',
  'editorRuler.foreground': '#E474',
  'editorSuggestWidget.selectedBackground': '#4AE4',
  'editorUnnecessaryCode.border': '#95B4',
  'settings.dropdownBackground': '#7164',
  'settings.checkboxBackground': '#38A4',
  'settings.numberInputBackground': '#38A4',
  'settings.textInputBackground': '#7164',
  'sideBar.border': '#FC64',
};
colors5 = {
  'editorInfo.border': '#4AE5',
  'editor.findRangeHighlightBackground': '#2355',
  'editor.findRangeHighlightBorder': '#52A5',
  'editor.findMatchBackground': '#38A5',
  'editor.focusedStackFrameHighlightBackground': '#2355',
  'editor.rangeHighlightBackground': '#2355',
  'editor.snippetFinalTabstopHighlightBackground': '#2355',
  'editor.snippetFinalTabstopHighlightBorder': '#2355',
  'editor.snippetTabstopHighlightBackground': '#2355',
  'editor.stackFrameHighlightBackground': '#2355',
  'peekViewResult.matchHighlightBackground': '#38A5',
  'menu.selectionBackground': '#EB55',
  'menubar.selectionBackground': '#2955',
  'scrollbarSlider.hoverBackground': '#38A5',
  'tab.hoverBackground': '#52A5',
  'titleBar.inactiveForeground': '#DCB5',
  'activityBar.dropBackground': '#7165',
  'debugToolBar.border': '#52A5',
  'editorGroup.border': '#FC65',
  'editorLineNumber.foreground': '#DCB5',
  'editorUnnecessaryCode.opacity': '#FFF5',
  'editorWidget.border': '#DCB5',
  'peekViewTitle.background': '#14B5',
  'scrollbarSlider.background': '#7165',
  'editor.selectionHighlightBackground': '#5275', // 6
  'editor.selectionBackground': '#53E5',// 6
  'menubar.selectionBorder': '#6185',// 6
  'list.activeSelectionBackground': '#38A5', // 7
  'list.hoverBackground': '#7165', // 7
  'list.focusBackground': '#7165', // 7
  'terminal.selectionBackground': '#3275', // 7
  
};
colors6 = {
};
colors7 = {
    
};
colors8 = {
};
colors9 = {
    'scrollbarSlider.activeBackground': '#AE49', // 8
    'tab.unfocusedInactiveModifiedBorder': '#E5D9',
  'extensionButton.prominentHoverBackground': '#7169',
  'tab.unfocusedActiveForeground': '#FD89',
  'tab.unfocusedInactiveForeground': '#FD89',
  focusBorder: '#7169',
  'inputOption.activeBackground': '#7169',
  'tab.inactiveForeground': '#FD89',
  'button.background': '#7169',
  'input.background': '#38A9',
  'dropdown.border': '#7169',
  'welcomePage.buttonBackground': '#7169',
  'minimapGutter.addedBackground': '#8B39', // A
  'minimapGutter.deletedBackground': '#B359', // A
  'minimapGutter.modifiedBackground': '#38A9', // A
  'activityBar.activeBackground': '#7169', // A
  'window.activeBorder': '#7169', // A
  'sideBarSectionHeader.border': '#7169', // A


};
                        colorsA = {
};
colorsB = {
  'editorInfo.foreground': '#6BFB',
  'editorMarkerNavigationError.background': '#B35B',
  'inputValidation.errorBorder': '#F45B',
  'inputValidation.errorForeground': '#FEDB',
  'inputValidation.warningForeground': '#FEDB',
  'notifications.foreground': '#DCBB',
  errorForeground: '#DCBB',
  'minimap.findMatchHighlight': '#F73B',
  'minimap.selectionHighlight': '#8DAB',
  'editor.findMatchHighlightBorder': '#38AB',
  'editor.findMatchBorder': '#34DB',
  'editorOverviewRuler.findMatchForeground': '#38AB',
  'listFilterWidget.background': '#426B',
  'listFilterWidget.noMatchesOutline': '#426B',
  'listFilterWidget.outline': '#426B',
  'editor.selectionHighlightBorder': '#52AB',
  'editor.snippetTabstopHighlightBorder': '#235B',
  'editor.wordHighlightBorder': '#8DAB',
  'editor.wordHighlightStrongBorder': '#E47B',
  'editorOverviewRuler.rangeHighlightForeground': '#F73B',
  'editorOverviewRuler.wordHighlightForeground': '#8DAB',
  'editorOverviewRuler.wordHighlightStrongForeground': '#E47B',
  'editorSuggestWidget.highlightForeground': '#6BFB',
  'list.highlightForeground': '#7B5B',
  'peekViewEditor.matchHighlightBackground': '#426B',
  'peekViewEditor.matchHighlightBorder': '#618B',
  'breadcrumb.activeSelectionForeground': '#EDEB',
  'list.activeSelectionForeground': '#EDCB',
  'editor.inactiveSelectionBackground': '#58EB',
  'list.inactiveSelectionForeground': '#DCBB',
  'editor.selectionForeground': '#DCBB',
  'menu.selectionBorder': '#52AB',
  'menu.selectionForeground': '#DCBB',
  'menubar.selectionForeground': '#DCBB',
  'peekViewResult.selectionForeground': '#EDAB',
  'selection.background': '#698B',
  'tab.unfocusedHoverBorder': '#38AB',
  'button.hoverBackground': '#38AB',
  'list.hoverForeground': '#DCBB',
  'tab.hoverBorder': '#38AB',
  'welcomePage.buttonHoverBackground': '#38AB',
  'tab.unfocusedActiveBorderTop': '#FB9B',
  'tab.unfocusedActiveModifiedBorder': '#F45B',
  'breadcrumb.focusForeground': '#DCBB',
  'list.focusForeground': '#FFFB',
  'editorLineNumber.activeForeground': '#DCBB',
  'editorLink.activeForeground': '#DCBB',
  'inputOption.activeBorder': '#EA2B',
  'panelTitle.activeBorder': '#38AB',
  'panelTitle.activeForeground': '#DCBB',
  'tab.activeForeground': '#DCBB',
  'textLink.activeForeground': '#64CB',
  'titleBar.activeForeground': '#DCBB',
  'activityBar.inactiveForeground': '#FECB',
  'panelTitle.inactiveForeground': '#DCBB',
  'tab.inactiveModifiedBorder': '#E3DB',
  'activityBar.foreground': '#FECB',
  'activityBarBadge.background': '#38AB',
  'activityBarBadge.foreground': '#FECB',
  'badge.background': '#38AB',
  'badge.foreground': '#FECB',
  'breadcrumb.foreground': '#DCBB',
  'button.foreground': '#FECB',
  descriptionForeground: '#DCBB',
  'editor.foreground': '#DCBB',
  'editorBracketMatch.border': '#AE4B',
  'editorOverviewRuler.addedForeground': '#8B3B',
  'editorOverviewRuler.border': '#38AB',
  'editorOverviewRuler.bracketMatchForeground': '#AE4B',
  'editorOverviewRuler.commonContentForeground': '#8DAB',
  'editorOverviewRuler.currentContentForeground': '#38AB',
  'editorOverviewRuler.deletedForeground': '#B35B',
  'editorOverviewRuler.incomingContentForeground': '#E47B',
  'editorOverviewRuler.modifiedForeground': '#38AB',
  'editorSuggestWidget.background': '#235B',
  'editorSuggestWidget.border': '#6BFB',
  'editorSuggestWidget.foreground': '#EDAB',
  'editorWidget.resizeBorder': '#38AB',
  'extensionButton.prominentBackground': '#38AB',
  'extensionButton.prominentForeground': '#FECB',
  foreground: '#DCBB',
  'input.border': '#EA2B',
  'input.foreground': '#FEDB',
  'input.placeholderForeground': '#FEDB',
  'list.invalidItemForeground': '#F42B',
  'menu.foreground': '#DCBB',
  'merge.border': '#38AB',
  'merge.commonHeaderBackground': '#8F7B',
  'merge.currentHeaderBackground': '#38AB',
  'merge.incomingHeaderBackground': '#E47B',
  'notificationCenterHeader.foreground': '#DCBB',
  'notificationLink.foreground': '#DCBB',
  'peekView.border': '#FC6B',
  'peekViewEditor.background': '#235B',
  'peekViewResult.fileForeground': '#EDAB',
  'peekViewResult.lineForeground': '#EDAB',
  'peekViewTitleDescription.foreground': '#EDAB',
  'pickerGroup.foreground': '#DCBB',
  'progressBar.background': '#38AB',
  'scrollbar.shadow': '#112B',
  'dropdown.foreground': '#DCBB',
  'settings.dropdownForeground': '#DCBB',
  'settings.checkboxForeground': '#DCBB',
  'settings.headerForeground': '#DCBB',
  'settings.modifiedItemIndicator': '#8B3B',
  'settings.numberInputForeground': '#DCBB',
  'settings.textInputForeground': '#DCBB',
  'sideBar.foreground': '#DCBB',
  'sideBarSectionHeader.foreground': '#DCBB',
  'sideBarTitle.foreground': '#DCBB',
  'statusBar.debuggingBackground': '#C60B',
  'statusBar.debuggingForeground': '#DCBB',
  'statusBar.foreground': '#DCBB',
  'statusBar.noFolderBackground': '#848B',
  'statusBar.noFolderForeground': '#DCBB',
  'statusBarItem.prominentBackground': '#694B',
  'statusBarItem.prominentForeground': '#DCBB',
  'textLink.foreground': '#6AFB',
  'textPreformat.foreground': '#DCBB',
  'textSeparator.foreground': '#DCBB',
  'widget.shadow': '#112B',
};
colorsC = {
  'editorGutter.addedBackground': '#8B3C',
  'editorGutter.deletedBackground': '#B35C',
  'editorGutter.modifiedBackground': '#38AC',
};
colorsD = {
  'editorHint.foreground': '#FC5D',
  'editorMarkerNavigationInfo.background': '#FC5D',
  'inputValidation.infoBorder': '#FC5D',
  'inputValidation.infoForeground': '#FC5D',
  'inputValidation.warningBorder': '#FC5D',
  'notificationsInfoIcon.foreground': '#FC5D',
  'editorOverviewRuler.infoForeground': '#FC5D',
  'problemsInfoIcon.foreground': '#FC5D',
  'editorOverviewRuler.selectionHighlightForeground': '#FC5D',
  'editorHoverWidget.foreground': '#DCBD',
  'peekViewTitleLabel.foreground': '#FC5D',
};
colorsE = {};
colorsF = {
  'gitDecoration.deletedResourceForeground': '#936F',
  'list.errorForeground': '#F36F',
  'minimap.errorHighlight': '#F36F',
  'editorError.foreground': '#F36F',
  'problemsErrorIcon.foreground': '#F36F',
  'notificationsErrorIcon.foreground': '#F36F',
  'tab.activeModifiedBorder': '#F36F',
  'editorOverviewRuler.errorForeground': '#F36F',
  'editorOverviewRuler.warningForeground': '#CF3F',
  'notificationsWarningIcon.foreground': '#CF3F',
  'problemsWarningIcon.foreground': '#CF3F',
  'tab.activeBorderTop': '#CF3F',
  'list.warningForeground': '#CF3F',
  'editorWarning.foreground': '#CF3F',
  'minimap.warningHighlight': '#CF3F',
};
